### ISSUE TITLE
Firefox extension repository

### ISSUE THREAD

**Issue by hyviquel** [varjolintu/keepassxc-browser#10]
I identified few problems with the version available in the official store of Firefox:
- [ ] The version is not up-to-date (0.2.1)
- [ ] It requires a version of firefox that does not exist yet (Compatible with Firefox 57+).
- [ ] The link given in the description of the extension is broken.

**Comment by varjolintu** [comment]
Thank you for the info. The only real problem I found was the link in the description. That is now fixed. I have already uploaded the latest version to the Firefox's official store but the admins haven't reviewed it yet. They have a reviewing process which is made every time a new version is uploaded. Sometimes it might take an hour, sometimes a few days.

You can download the latest .crx from [releases](https://github.com/varjolintu/keepassxc-browser/releases) page. It's compatible with Firefox Nightly (56.0a1 and later). The official Firefox Add-on page shows the compatibility with Firefox 57 because it will be the first stable version that will support WebExtensions reliably.

**Comment by hyviquel** [comment]
Ok, thanks for the information!
