### ISSUE TITLE
Proper Install Guide for Firefox

### ISSUE THREAD

**Issue by tk-shockwave** [varjolintu/keepassxc-browser#15]
It would be good to have a proper install guide for firefox since I couldn't get the plugin connect to the keepassxc instance/database. 

The site and also the readme is not giving any clue what should be done .. currently after starting firefox the plugin eats all RAM/CPU ..no way to configure the database manually ..so how it works how it is supposed to setup and error handling? is this something we have to guess and riddle and find out buy mindreading?

**Comment by varjolintu** [comment]
I'm sorry for not writing such a guide. The reason for that is that the extension currently works only with Firefox Nightly, and it seems that the current Nightly does something that screws up some extensions, keepassxc-browser included. The Nightly few days before worked normally.

I have uploaded the version 0.2.8 to the official Mozilla Add-on page but the release review delay can be from days to weeks, so I can't really help about that. The version 0.2.8 should work with Firefox 55 when it's officially released.

At this point the following method is the only way to get the extension work with stable Firefox if Firefox Nightly doesn't load it correctly:
- Download the sources from the GitHub page
- Go to about:debugging#addons and press Load Temporary Add-on
- Find the manifest.json inside the sources and open it

Now the extension should be loaded. There's still a drawback that because the extension is temporary you have to connect it every time to your database again. And for some reason Firefox uses the Native Messaging JSON file as a command line parameter when the extension is loading KeePassXC. This means the JSON files is being opened in own tab because KeePassXC thinks it's a valid database. Just ignore the tab or close it. Be sure to select your database tab and open it before connecting the extension through Firefox.

If Firefox Nightly opens the extension normally and opens KeePassXC, you can use the following method instead:
- Drag'n drop the extension .crx file to the Add-on page (about:addons)
- Close Nightly and start stable Firefox

This way the extension is loaded normally but it might get disabled from time to time because it's not "verified". But luckily this will be fixed when the 0.2.8 version lands to the official Add-on page.

I'm updating the README if there's any big problems left after 0.2.8.

Hope this helps!

**Comment by tk-shockwave** [comment]
Hello,

thanks for your reply. Do I need the keepassxc-proxy?

I enabled just the http interface in keepassxc but now I just get 
timeout issue in firefox.
I'm using Windows 10 x64 and latest nightly of firefox.

Thanks in advance

**Comment by varjolintu** [comment]
No, you don't need keepassxc-proxy (installing that needs a few manual operations anyway).

You must enable the Browser extension (Native Messaging) from KeePassXC settings and enable Firefox from the Supported browsers tab.

If you have no idea what I'm talking about, you are using the official release of KeePassXC. This browser extension needs an unofficial version which can be downloaded [here](https://github.com/varjolintu/keepassxc/releases). The same feature will be released in the official KeePassXC in the future.

If you want to use the old HTTP inferface, please use [passifox](https://github.com/pfn/passifox).

**Comment by cjustin88** [comment]
> Be sure to select your database tab and open it before connecting the extension through Firefox.
Will future development enable the possibility of opening KeepassXC after Firefox (and the extension) have already been loaded? Right now it is kind of inconvenient to have to close Firefox and KeepassXC, open Firefox first, then unlock, then connect, in case I close KeepassXC or didn't unlock it upon Firefox startup.

**Comment by varjolintu** [comment]
@cjustin88, This is the unfortunate drawback of Native Messaging: the browser extension needs to launch the application it connects to. Luckily it's already possible to use an alternative method which is a proxy application which transfers the messages between the browser extension and KeePassXC without the need of any restarts. It connects on-the-fly. Currently there are three possible solutions you can use:
- [keepassxc-proxy](https://github.com/varjolintu/keepassxc-proxy) (python)
- [keepassxc-proxy-rust](https://github.com/varjolintu/keepassxc-proxy-rust) (rust)
- [chrome_native_messaging_host](https://github.com/mauron85/chrome_native_messaging_host) (C#)

Or you can write your own proxy application if you don't find those trustworthy :)

If you want to use a proxy application you must edit the Native Messaging JSON file installed for Firefox and change the path to point the proxy application instead of KeePassXC (or use a install script provided by keepassxc-proxy). More information about these files can be found [here](https://developer.chrome.com/extensions/nativeMessaging).

To enable proxy application support in the KeePassXC fork, you must go to Application Settings -> Browser extension (Native Messaging) -> Advanded tab -> Check the Enable support for proxy application between KeePassXC and browser extension.

**Comment by varjolintu** [comment]
The latest version 0.2.8 is now released in AMO. It works with the latest stable Firefox (55.x). I will fix the .json tab issue with KeePassXC next. Closing this issue for now.

**Comment by varjolintu** [comment]
Please see this [wiki page](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-current-beta-build) if you have still problems connecting the database.

**Comment by prometheanfire** [comment]
@varjolintu that wiki page does not exist

**Comment by varjolintu** [comment]
@prometheanfire The new URL is [https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-keepassxc-browser](https://github.com/varjolintu/keepassxc-browser/wiki/Connecting-the-database-with-keepassxc-browser).
