### ISSUE TITLE
Unable to connect multiple browsers to one database

### ISSUE THREAD

**Issue by moghingold** [varjolintu/keepassxc-browser#24]
The nature of my work often requires me to use multiple browsers. Because of this, it would be incredibly useful if all my open browsers that have connected to KeePassXC could be connected to it simultaneously. The current workflow goes like this:

1. Click on the keepassxc-browser icon in my add-on bar, and click "reload"
1a. If KeePassXC is already open, I will have to close it first to allow the extension to launch the application, as it is deliberately locked to one instance.
1b. Right off the bat, I don't think I'm alone in saying that the correct behavior for the "reload" button should be to try to re-connect to the already-opened instance of KeePassXC.
2. After unlocking the database, the first browser will be connected and able to auto-fill usernames and passwords as-expected.
3. Go to the other browser (if the first one was Firefox, now do Chrome, or vice versa) and click "reload."
3a. If KeePassXC is already open, I will have to close it first to allow the extension to launch the application, as it is deliberately locked to one instance. _This breaks the connection to the browser chosen in step 1_
3b. Again, expected behavior would be that keepassxc-browser connect to the available instance of KeePassXC.
4. If, instead of clicking "reload," the user clicks on "Settings" and then navigates to "Connected Databases," the user can click on the "Connect" button.
4a. Expected behavior here would be that the keepassxc-browser instance connects to the already existing instance of KeePassXC without requiring the user to reload KeePassXC.
4b. Actual behavior, as far as I can tell, is nothing. Absolutely nothing. This does not change whether the browser is Chrome or Firefox.

I'm using the latest release from https://github.com/varjolintu/keepassxc/releases on MacOS. Again, both browsers (Chrome and Firefox) are perfectly capable of connecting keepassxc-browser to KeepPassXC...but both of them cannot do so at the same time.

**Comment by varjolintu** [comment]
This happens because Native Messaging can connect to one application at time, which means Firefox -> KeePassXC or Chrome -> KeePassXC. That's why I started the project [keepassxc-proxy](https://github.com/varjolintu/keepassxc-proxy). This means KeePassXC listens to a UDP port which allows multiple clients simultaneously.

This feature has been on my list for months but because the lack of time I still haven't finished it. So you must have to wait a while. But this is definitely my top priority at the time because I personally need the feature too.

I have been planning to improve the keepassxc-proxy to use Unix sockets instead of UDP in linux/unix/macos and named pipes in Windows, but that step comes after the multiple client support.

**Comment by moghingold** [comment]
That makes sense. Thank you for the update! I appreciate your attention to the issue.

**Comment by varjolintu** [comment]
Just wanted to tell some news. I already have a working implementation of this feature. Just needs a little testing and few small issues resolved. If lucky it will be available next week.

**Comment by moghingold** [comment]
Thank you!

**Comment by varjolintu** [comment]
This is now completed and available from the branch sources. Also keepassxc-proxy is updated.
