### ISSUE TITLE
Enhancement: Allow TOTP to be selected if user/pass is not present on the page

### ISSUE THREAD

**Issue by iceman73** [varjolintu/keepassxc-browser#50]
Amazon, Google and Namecheap, all don't offer to enter the TOTP in the same login page for user and password, this is an issue, as when the TOTP page loads, the Keepass-Browser extention context menu is not available, so you cannot enter the TOTP password, without opening Keepassxc and copying it from there.

## Expected Behavior
When Amazon TOTP page loads, have the context menu available to enter the TOTP into the field
![image](https://user-images.githubusercontent.com/2061265/34675535-ea4265ce-f457-11e7-9577-3dce2b7a62ed.png)

## Current Behavior
There is no Context page when the TOTP page comes up without user/password fields on the page. The addon does recognize that the entry for amazon should be utilized but clicking the addon Icon in the browser bar, does not fill the TOTP value. Utilizing the KPH: {TOTP} tag

## Possible Solution
When Amazon TOTP page loads, have the context menu available to enter the TOTP into the field
![image](https://user-images.githubusercontent.com/2061265/34675535-ea4265ce-f457-11e7-9577-3dce2b7a62ed.png)

## Steps to Reproduce (for bugs)

1. Add amazon.com entry to keepassxc
2. ensure that TOTP is setup and in advanced add "KHP: {TOTP}" value "{TOTP"
3. Goto amazon.com
4. Signin, user/pass
5. When at TOTP page, right click to try and enter TOTP

## General Info
KeePassXC fork - 2.2.4
keepassxc-browser - 0.4.5

Operating system: Windows 10
Browser: Firefox

**Comment by varjolintu** [comment]
Fixed with https://github.com/varjolintu/keepassxc-browser/commit/ab0871ee0283e7e86200b392b873303990e55ecf and https://github.com/varjolintu/keepassxc-browser/commit/b90797e29e4d40483bbba63128aef55445bf37d5.

However to get this working with some sites you'll need an extra step. For example amazon.com needs own entry (username and password are not needed for this) with the URL `https://www.amazon.com/ap/mfa` wit the `KPH: {TOTP}` added. For some sites like Protonmail this is not needed. Without the URL the correct TOTP (or credentials) cannot be received.

And I also found a bug with Firefox. Some of these input fields haven't got context menu visible even when the values `editable` and `password` is enabled. With Chromium there is no such problem. Also it's not a good solution to add contextType `all` when using Firefox. I'll contact the Mozilla team for a solution.

Because of this bug I added a new keyboard shortcut for the TOTP filling. It works with `Alt+Shift+T` on Firefox under Windows. These changes will be released in version 0.4.9. If you want to try them out you can download the sources from the develop branch.
