### ISSUE TITLE
Chrome/Chromium extension link is broken

### ISSUE THREAD

**Issue by dreamlayers** [varjolintu/keepassxc-browser#57]
The Chrome/Chromium extension link in README.md goes to https://chrome.google.com/webstore/detail/keepassxc-browser/iopaggbpplllidnfmcghoonnokmjoicf , which is 404 not found. I can find KeePassXC-Browser at https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk (note different ID at the end). But, I'm not going to install this security critical extension from an even slightly questionable link with 3 reviews and 245 users.

**Comment by varjolintu** [comment]
My repository might not be up-to-date. Please follow the new official repository instead:
[https://github.com/keepassxreboot/keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser). If you look at the KeePassXC website you can see the latter URL is correct. The first one pointed to my older version of the extension. ID's had to be changed because everything was put under KeePassXC Team instead of my name.

This repository will be changed to a fork soon.
