### ISSUE TITLE
Let user modify command-line to start KeePassXC

### ISSUE THREAD

**Issue by rugk** [varjolintu/keepassxc-browser#8]
Allowing this could allow the user to use different types of privilege separation in order to protect the passwords from unauthorized access.

The privilege separation could be done with `sudo`, with `qrexec`/Qubes. See e.g.:
``` 
sudo -u user keeepassxc
# OR:
/root/qrexec-wrapper.sh
``` 

In `/root/qrexec-wrapper.sh`:
```sh
#!/bin/sh
qvm-run --pass-io -- <jump VM> "keeepassxc"
```

(idea adapted from https://github.com/borgbackup/borg/issues/2679#issuecomment-308573135, by @enkore)

**Comment by varjolintu** [comment]
When looking at this [page](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) there's a following explanation:

> On Linux and Mac, Chrome passes one argument to the native app, which is the origin of the add-on that started it, in the form: chrome-extension://[extensionID]. This enables the app to identify the add-on.

> On Windows, Chrome passes two arguments: the first is the origin of the add-on, and the second is a handle to the Chrome native window that started the app

So there's no possibility to transfer any command line arguments to the KeePassXC process. The only possibility is to use a proxy application (which is supported by my KeePassXC fork and this extension). The proxy application connects to an existing KeePassXC process. You can try an experimental version [here](https://github.com/varjolintu/keepassxc-proxy) and test if it can connect to KeePassXC. Both Qt and python versions are available. Or then you can write your own :)

**Comment by rugk** [comment]
Cannot you also just use a shell script as a proxy here? As my second example already shows, …

**Comment by varjolintu** [comment]
Yes you can. I just tested it. Just make a script that starts KeePassXC and change the path from installed .json file to that script. The only drawback with this solution is that when shutting down the browser it cannot reconnect to KeePassXC when started again. KeePassXC must be restarted also.

Of course there's a possibility to make this as a configuration feature in KeePassXC. I'm already in favor to move the .json installing to KeePassXC side because now there's always an extra step when installing the browser extension.
